name: e_commerce_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  velocity_x: ^4.1.1

dev_dependencies:
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  image_picker: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
